#!/bin/sh

logger -t h5000m-defaults "设置默认 LAN 地址为 192.168.10.1"
uci -q set network.lan.proto='static'
uci -q set network.lan.ipaddr='192.168.10.1'
uci -q set network.lan.netmask='255.255.255.0'
uci -q commit network

logger -t h5000m-defaults "设置 root 默认密码"
if command -v chpasswd >/dev/null 2>&1; then
	echo 'root:admin' | chpasswd
else
	(printf 'admin\nadmin\n' | passwd root) >/dev/null 2>&1 || true
fi

logger -t h5000m-defaults "清理固件内的 QModem 软件源"
if [ -f /etc/apk/repositories.d/distfeeds.list ]; then
	sed -i '/\/qmodem\//d;/ qmodem[ _-]/d;/ qmodem$/d' /etc/apk/repositories.d/distfeeds.list
fi

if [ -f /etc/opkg/distfeeds.conf ]; then
	sed -i '/\/qmodem\//d;/ qmodem[ _-]/d;/ qmodem$/d' /etc/opkg/distfeeds.conf
fi

exit 0
