#!/bin/sh

PASSWALL2_CONFIG="/etc/config/passwall2"

[ -d /usr/share/passwall2 ] || exit 0

logger -t h5000m-passwall2 "Apply default PassWall2 placeholder shunt configuration"

if [ ! -s "${PASSWALL2_CONFIG}" ] && [ -f /usr/share/passwall2/0_default_config ]; then
	cp /usr/share/passwall2/0_default_config "${PASSWALL2_CONFIG}"
fi

cat > "${PASSWALL2_CONFIG}" <<'EOF'
config global
	option enabled '1'
	option node_socks_port '1070'
	option localhost_proxy '1'
	option client_proxy '1'
	option socks_enabled '0'
	option acl_enable '0'
	option node 'h5000m_shunt'
	option direct_dns_protocol 'auto'
	option direct_dns_query_strategy 'UseIP'
	option remote_dns_protocol 'tcp'
	option remote_dns '1.1.1.1'
	option remote_dns_query_strategy 'UseIPv4'
	option dns_hosts 'cloudflare-dns.com 1.1.1.1
dns.google.com 8.8.8.8'
	option log_node '1'
	option loglevel 'warning'

config global_haproxy
	option balancing_enable '0'

config global_delay
	option start_daemon '1'
	option start_delay '10'

config global_forwarding
	option tcp_no_redir_ports 'disable'
	option udp_no_redir_ports 'disable'
	option tcp_redir_ports '1:65535'
	option udp_redir_ports '1:65535'
	option accept_icmp '0'
	option prefer_nft '1'
	option tcp_proxy_way 'redirect'
	option ipv6_tproxy '0'

config global_xray
	option sniffing_override_dest '0'

config global_other
	option auto_detection_time 'tcping'
	option show_node_info '0'

config global_rules
	option auto_update '0'
	option geosite_update '1'
	option geoip_update '1'
	option v2ray_location_asset '/usr/share/v2ray/'
	option geoip_url 'https://github.com/Loyalsoldier/geoip/releases/latest/download/geoip.dat'
	option geosite_url 'https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat'

config global_app
	option geoview_file '/usr/bin/geoview'
	option xray_file '/usr/bin/xray'
	option hysteria_file '/usr/bin/hysteria'
	option sing_box_file '/usr/bin/sing-box'

config global_subscribe
	option filter_keyword_mode '1'

config global_singbox

config shunt_rules 'PrivateIP'
	option remarks 'PrivateIP'
	option network 'tcp,udp'
	option ip_list '10.0.0.0/8
127.0.0.0/8
198.51.100.0/24
192.0.0.0/24
169.254.0.0/16
224.0.0.0/3
192.168.0.0/16
192.88.99.0/24
100.64.0.0/10
172.16.0.0/12
0.0.0.0/8
192.0.2.0/24
203.0.113.0/24'

config shunt_rules 'apple_services'
	option remarks '苹果服务'
	option network 'tcp,udp'
	option domain_list 'geosite:apple
geosite:apple@cn'

config shunt_rules 'microsoft_services'
	option remarks '微软服务'
	option network 'tcp,udp'
	option domain_list 'geosite:microsoft
geosite:microsoft@cn
geosite:onedrive'

config shunt_rules 'China'
	option remarks 'China'
	option network 'tcp,udp'
	option domain_list 'geosite:cn'
	option ip_list 'geoip:cn'

config shunt_rules 'speedtest_services'
	option remarks '测速服务'
	option network 'tcp,udp'
	option domain_list 'geosite:speedtest'

config shunt_rules 'ai_dev_services'
	option remarks 'AI与开发服务'
	option network 'tcp,udp'
	option domain_list 'geosite:openai
geosite:category-ai-!cn
geosite:category-dev
geosite:github'

config shunt_rules 'streaming_services'
	option remarks '海外流媒体'
	option network 'tcp,udp'
	option domain_list 'geosite:youtube
geosite:netflix
geosite:disney
geosite:hbo
geosite:primevideo
geosite:spotify
geosite:tiktok
geosite:bahamut
geosite:pixiv'
	option ip_list 'geoip:netflix'

config shunt_rules 'social_services'
	option remarks '海外社交通讯'
	option network 'tcp,udp'
	option domain_list 'geosite:telegram
geosite:discord
geosite:twitter
geosite:facebook
geosite:instagram'
	option ip_list 'geoip:telegram
geoip:twitter
geoip:facebook'

config shunt_rules 'google_services'
	option remarks '谷歌服务'
	option network 'tcp,udp'
	option domain_list 'geosite:google'
	option ip_list 'geoip:google'

config shunt_rules 'paypal_services'
	option remarks 'PayPal'
	option network 'tcp,udp'
	option domain_list 'geosite:paypal'

config shunt_rules 'geolocation_not_cn'
	option remarks '非中国大陆'
	option network 'tcp,udp'
	option domain_list 'geosite:geolocation-!cn'

config nodes 'lax'
	option remarks 'lax'
	option type 'Xray'
	option protocol 'vless'
	option address 'example-lax.example.com'
	option port '443'
	option uuid '00000000-0000-0000-0000-000000000000'
	option encryption 'none'
	option flow ''
	option tls '1'
	option tls_serverName 'example-lax.example.com'
	option utls '1'
	option fingerprint 'chrome'
	option reality '0'
	option transport 'raw'
	option tcp_guise 'none'
	option tcp_fast_open '0'
	option tcpMptcp '0'
	option domain_strategy 'UseIPv4'

config nodes 'tky'
	option remarks 'tky'
	option type 'Xray'
	option protocol 'vless'
	option address 'example-tky.example.com'
	option port '443'
	option uuid '00000000-0000-0000-0000-000000000000'
	option encryption 'none'
	option flow ''
	option tls '1'
	option tls_serverName 'example-tky.example.com'
	option utls '1'
	option fingerprint 'chrome'
	option reality '0'
	option transport 'raw'
	option tcp_guise 'none'
	option tcp_fast_open '0'
	option tcpMptcp '0'
	option domain_strategy 'UseIPv4'

config nodes 'auto_select'
	option remarks '自动选择代理'
	option type 'Xray'
	option protocol '_balancing'
	list balancing_node 'lax'
	list balancing_node 'tky'
	option balancingStrategy 'leastPing'
	option fallback_node 'lax'
	option useCustomProbeUrl '1'
	option probeUrl 'https://www.gstatic.com/generate_204'
	option probeInterval '1m'

config nodes 'h5000m_shunt'
	option remarks '总分流'
	option type 'Xray'
	option protocol '_shunt'
	option domainStrategy 'IPOnDemand'
	option domainMatcher 'hybrid'
	option write_ipset_direct '1'
	option enable_geoview_ip '1'
	option PrivateIP '_direct'
	option apple_services '_direct'
	option microsoft_services '_direct'
	option China '_direct'
	option speedtest_services '_direct'
	option ai_dev_services 'auto_select'
	option streaming_services 'lax'
	option social_services 'auto_select'
	option google_services 'auto_select'
	option paypal_services 'lax'
	option geolocation_not_cn 'auto_select'
	option default_node 'auto_select'

EOF

uci -q commit passwall2
/etc/init.d/passwall2 enable >/dev/null 2>&1 || true

exit 0
