#!/bin/sh

[ "${ACTION}" = "ifup" ] || [ "${ACTION}" = "ifupdate" ] || exit 0

case "${INTERFACE}" in
	wan|wan6|USB|USBv6)
		;;
	*)
		exit 0
		;;
esac

logger -t h5000m-wan-priority "同步 WAN 与 5G 备用出口优先级"

uci -q set network.wan.metric='10'
uci -q set network.wan6.metric='10'
uci -q set network.USB.metric='50'
uci -q set network.USBv6.metric='50'
uci -q delete network.wan5g
uci -q delete network.wan5g6
uci -q commit network
